[project]
name = "routes-database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.10",
    "pandas>=2.2.3",
    "polars>=1.23.0",
    "uvicorn[standard]>=0.34.0",
]
